version: "3.3"
services:
  job-suggester:
    build: ./
    working_dir: /app
    ports:
      - "8080:8080"
    command:
      uvicorn --host ${HOST:-"0.0.0.0"} --port ${PORT:-"8080"} app.main:app --reload
      
